import {createState,transition,view,attachSources} from '../frontend/story.mjs';
import {SOURCE_LENSES} from '../frontend/branches.mjs';
import {safeZhihuUrl,verifySession,GuideError,digest} from './guide.mjs';
const concerns={direction:'兴趣与方向',time:'时间安排',budget:'生活开支'};
const topics={study_plan:'大学考研翻盘 大一 真实经历',project:'大学生 项目 失败 复盘 亲身经历',rules:'大学转专业 申请 真实经历',ask_source:'大学第一次失败 如何求助 真实经历',carry_alone:'大学备考 压力 失败 真实经历',talk_roommate:'大学室友 项目 关系 复盘 真实经历',exam_full:'考研失败 错过实习 真实经历',balance:'大学考研 实习 平衡 真实经历',reply:'考研失败 毕业迷茫 真实经历',ask:'大学转专业 亲身经历',try:'大学探索兴趣 实践 经历',transfer_prepare:'大学转专业 申请 成功 失败 经历',course:'大学旁听 跨专业 课程 体验',practice:'大学期间做项目是一种怎样的体验',rethink:'大学迷茫 课程 时间安排 经历',prepare:'考研准备 时间 复盘 经历',intern:'大学实习 岗位体验 复盘',portfolio_intern:'大学生 作品 实习 投递 复盘',study_gap:'实习 基础不足 学习 经历',budget_plan:'大学 经济压力 备考 求职 经历',small_practice:'大学生 低成本 实践 探索',admitted:'研究生 录取 真实感受 经历',exam:'考研 备考 失败 复盘',civil:'应届生 考公 备考 经历',work:'大学毕业 第一份工作 经历',gap:'大学毕业 gap year 经历',lost:'大学毕业 迷茫 经历',jobless:'毕业 找不到工作 经历',delay:'延期毕业 亲身经历'};
const clean=s=>String(s||'').replace(/<[^>]*>/g,' ').replace(/\s+/g,' ').trim();
export const pathKey=data=>JSON.stringify((data.history||[]).map(h=>[h.choice_id,h.source_id,h.source_snapshot||null,h.effort??2]));
export async function loadSnapshot(id,{store,session,current,data,now}){const item=(await store.get('source-snapshot:'+id,now))?.value;if(!item||item.sid!==session.id||item.branch!==current.branch_id||item.choice!==current.choice_id||item.path!==await digest(pathKey(data))||item.effort!==(data.effort??2))throw new GuideError('INVALID_SOURCE_SNAPSHOT','这组经历已过期或不属于当前路径。',400);return item.references;}
export async function replaySigned(data,{secret,store,now=Date.now()},select=true){
 const session=await verifySession(data.token,secret,now);if(!session)throw new GuideError('SESSION_EXPIRED','请重新连接这次体验。',401);
 if(!Array.isArray(data.history)||data.history.length>3)throw new GuideError('INVALID_PATH','路径不完整。');let state=createState();const prior=[];
 const step=(type,extra={})=>{state=transition(state,{type,revision:state.revision,node_id:view(state).node_id,...extra});};
 try{for(const h of [...data.history,{choice_id:data.choice_id,source_id:data.source_id,source_snapshot:data.source_snapshot,effort:data.effort}]){
 step('choose',{choice_id:h.choice_id,effort:h.effort??2});if(h.source_snapshot){const refs=await loadSnapshot(h.source_snapshot,{store,session,current:view(state),data:{history:prior,effort:h.effort},now});state=attachSources(state,refs,h.source_snapshot);}
 if(prior.length===data.history.length){if(select)step('select',{source_id:h.source_id});break;}step('select',{source_id:h.source_id});step('advance');prior.push(h);
 }}catch(e){if(e instanceof GuideError)throw e;throw new GuideError('INVALID_PATH','选择或来源不属于这条路径。');}
 return {state,current:view(state),session};
}
function lensFor(summary,focus){
 const rules=[[/补修|补课|基础|听不懂/,'先试一节目标专业的基础课','看清想象与学习任务的差别','要补基础，也要照顾现有课程','academic','你先试了一次基础练习，把不理解的地方列出来，再决定是否继续。'],[/支出|经济压力|生活费|收入空档/,'先算清一个月的生活预算','知道能为探索留出多少余地','可能要缩小原来的计划','sustainable','你写下必要支出和可用时间，先让下一步能持续。'],[/后悔|纠结|兴趣|擅长/,'分别记下喜欢与擅长的任务','分清兴趣、想象与实际体验','需要亲自做一次验证','sustainable','你列出喜欢和擅长的任务，挑一项安排短体验，暂时不急着下结论。'],[/面试|投递|岗位|实习/,'找一位从业者核实日常任务','用真实任务理解一个方向','联系需要时间，也可能没有回复','practice','你准备了一个关于岗位日常的问题，先了解再决定是否尝试。'],[/备考|考研|复试/,'试一周复习，再看能否持续','得到学习节奏的实际反馈','挤占其他安排，考试结果仍不定','academic','你为复习安排了一周的试行期，留一天回看哪些安排可持续。'],[/绩点|申请|转专业|教务/,'核对本校条件与申请日期','查清可选机会','要核实信息，个人经验不能照搬','academic','你核对本校现行条件与日期，把尚不清楚的事项整理成问题。']];
 const match=rules.find(([pattern])=>pattern.test(summary));if(match){const [,label,gain,cost,focus,text]=match;return {label,gain,cost,focus,text};}return {...SOURCE_LENSES[focus==='academic'?'major_first':'college_planning']};
}
export async function normalizeItems(items,focus,choiceId=''){const urls=new Set(),out=[];
 for(const raw of items){const url=safeZhihuUrl(raw.Url);if(!url)continue;const canonical=new URL(url);canonical.search='';if(urls.has(canonical.href)||!(/\/answer\/\d+|\/p\/\d+/.test(canonical.pathname)))continue;const title=clean(raw.Title).slice(0,140),summary=clean(raw.ContentText).slice(0,1000);if(!title||summary.length<35)continue;
 // Suppress obvious recruitment/service adverts; this heuristic is not an authenticity guarantee.
 if(/深研未来|青途号|筑境产学研|教育咨询有限公司|扫码|加微信|咨询报名|私信领取/.test(title+' '+summary))continue;urls.add(canonical.href);
 const sentences=summary.split(/(?<=[。！？])/).map(x=>x.trim()).filter(x=>x.length>12&&x.length<180);const score=x=>(/我|自己/.test(x)?2:0)+(/但是|结果|反而|后悔|失去|没|失败|代价|难|发现|意识到/.test(x)?4:0)+(/课程|准备|实习|专业|毕业|实践/.test(x)?1:0)-Math.max(0,x.length-85)/30;
 const meaningful=[...sentences].sort((a,b)=>score(b)-score(a))[0]||summary;const lens=lensFor(meaningful+' '+summary.slice(0,200),focus);const personal=/我(?:在|的|是|曾|没有|以为|决定|发现|转|本|大)/.test(summary);const anchors={ask:/转专业|专业选择/,try:/兴趣|探索|尝试|实践|课外/,transfer_prepare:/转专业/,course:/旁听|跨专业|专业课/,practice:/项目|实践|创业|实习|作品|科研|大创|gamejam/i,rethink:/时间|安排|节奏|迷茫/,prepare:/考研|备考|复习/,intern:/实习|岗位|职场/,portfolio_intern:/实习|投递|作品/,study_gap:/基础|实习|学习/,budget_plan:/开支|生活费|经济|兼职|花钱|家庭|收入|就业|考研/,small_practice:/项目|实践|兴趣|低成本|试错/,admitted:/研究生|读研|录取/,exam:/考研|备考|复试/,civil:/考公|公务员/,work:/第一份工作|毕业|职场|求职/,gap:/gap|间隔年|休整|间隔一年/i,lost:/毕业|迷茫/,jobless:/待业|失业|找不到|就业|求职/,delay:/延期|延毕|延迟毕业/};const anchor=anchors[choiceId];const titleRelevant=!anchor||anchor.test(title);if(choiceId==='practice'&&!/大学|大一|大二|大三|本科|同学|学生|在校|校园/.test(title+' '+summary))continue;if(anchor&&!titleRelevant&&!anchor.test(summary.slice(0,350)))continue;const relevance=titleRelevant?5:0;
 out.push({id:'live_'+(await digest(canonical.href)).slice(0,20),title,summary,url,author:clean(raw.AuthorName)||'署名见原文',type:'知乎检索摘要',short_summary:meaningful.length>88?meaningful.slice(0,85)+'…':meaningful,lens,question:'这段经历里的哪一步，适合在你的条件下先试一次？',action:lens.label+'，记下一个需要核实的问题。',retrieved_at:new Date().toISOString(),rank:relevance+(personal?2:0)});
 }return out.sort((a,b)=>b.rank-a.rank).map(({rank,...r})=>r);
}
export async function findSources(data,{secret,store,fetcher=fetch,ip='unknown',now=Date.now(),signal}){
 const {current,session}=await replaySigned(data,{secret,store,now},false);const choice=current.node.choices.find(c=>c.id===current.choice_id);const concern=concerns[data.concern]?data.concern:'direction',angle=Number.isInteger(data.angle)?Math.max(0,Math.min(2,data.angle)):0;
 const topic=topics[choice.id]||(choice.focus==='academic'?'大学 跨专业 课程 亲身体验':choice.focus==='practice'?'大学实习 真实经历':/预算|支出/.test(choice.label)?'大学生 生活开支 亲身经历':'大学 探索兴趣 亲身经历');
 const query=topic+(choice.id==='practice'?'':' '+concerns[concern])+(['',' 踩坑 失败',' 转折 改变'][angle]);const key='search-2.1q5:'+await digest(query);const existing=await store.get(key,now);let references=existing?.state==='ready'?existing.value:null,mode='cached',reason;
 if(!references){const day=new Date(now+8*3600000).toISOString().slice(0,10);const iphash=(await digest(secret+ip)).slice(0,20);if(!await store.reserve('search-session:'+session.id,12,now+7200000)||!await store.reserve('search-ip:'+day+iphash,32,now+86400000)||!await store.reserve('search-day:'+day,300,now+86400000))return {mode:'curated',references:[],reason:'检索额度暂时用完，可继续使用预整理经历。'};
 if(!await store.claim(key,now))return {mode:'curated',references:[],reason:'这类经历正在检索，稍后可换一组。'};
 try{const response=await fetcher('https://developer.zhihu.com/api/v1/content/zhihu_search?'+new URLSearchParams({Query:query,Count:'10'}),{headers:{Authorization:'Bearer '+secret,'X-Request-Timestamp':String(Math.floor(now/1000))},signal:signal?AbortSignal.any([signal,AbortSignal.timeout(4500)]):AbortSignal.timeout(4500)});if(!response.ok)throw Error('search unavailable');const r=await response.json();if(r.Code!==0)throw Error('search failed');references=await normalizeItems(r.Data?.Items||[],choice.focus,choice.id);if(!references.length)throw Error('no usable excerpts');await store.set(key,references,now);mode='live';}catch{return {mode:'curated',references:[],reason:'暂未获得可用的新经历，先保留预整理内容。'};}finally{await store.release(key);}}
 const seen=new Set(Array.isArray(data.seen)?data.seen.slice(0,50):[]);const priority=r=>concern==='time'?Number(/课余|时间|熬夜|安排|平衡/.test(r.summary)):concern==='budget'?Number(/生活费|支出|开支|经济|钱|收入/.test(r.summary)):Number(/兴趣|方向|喜欢|擅长/.test(r.summary));references=[...references].sort((a,b)=>Number(seen.has(a.id))-Number(seen.has(b.id))||priority(b)-priority(a));
 const snapshot_id=(await digest(session.id+key+concern+pathKey(data)+current.choice_id+(data.effort??2))).slice(0,48);const saved=await store.get('source-snapshot:'+snapshot_id,now);if(saved?.value){const seenAgain=new Set(Array.isArray(data.seen)?data.seen:[]);return {mode,references:[...saved.value.references].sort((a,b)=>Number(seenAgain.has(a.id))-Number(seenAgain.has(b.id))),snapshot_id,query,total:saved.value.references.length,retrieved_at:saved.value.references[0]?.retrieved_at};}if(!await store.reserve('snapshot-session:'+session.id,40,now+7200000))return {mode:'curated',references:[],reason:'本次探索已较多，可继续当前经历。'};await store.set('source-snapshot:'+snapshot_id,{sid:session.id,branch:current.branch_id,choice:current.choice_id,path:await digest(pathKey(data)),effort:data.effort??2,references},now);
 return {mode,references,snapshot_id,query,total:references.length,retrieved_at:references[0]?.retrieved_at};
}
