import test from 'node:test';import assert from 'node:assert/strict';
import {runGuide,issueSession,replayContext,guideHttp,safeZhihuUrl,verifySession} from '../backend/guide.mjs';
import {localStore} from '../backend/local-store.mjs';
const secret='test-only-secret-with-no-real-credentials';
const data=async(question='我担心试错耽误学习，怎么办？')=>({history:[],choice_id:'study_plan',source_id:'major_first',question,token:await issueSession(secret)});
const answer={reflection:'先把试错压到一次短体验，不急着决定整个专业方向。',next_step:'这周找目标专业同学问一门课程的实际任务，约定二十分钟。',question:'目前最担心的是时间还是成绩？',source_ids:['major_first']};
const response=(a=answer)=>Response.json({choices:[{message:{content:JSON.stringify(a)}}]});
test('guide verifies token and replays history before any model call',async()=>{let calls=0;const options={secret,store:localStore(),fetcher:async()=>{calls++;return response();}};const input=await data();await assert.rejects(runGuide({...input,source_id:'jobless'},options),{code:'INVALID_PATH'});await assert.rejects(runGuide({...input,token:input.token+'x'},options),{code:'SESSION_EXPIRED'});assert.equal(calls,0);assert.equal(await verifySession(await issueSession(secret,0),secret),null);});
test('live answer has validated sources, exact upstream headers and context-aware cache',async()=>{let calls=0;const store=localStore();const fetcher=async(url,init)=>{calls++;assert.equal(url,'https://developer.zhihu.com/v1/chat/completions');assert.equal(init.headers.Authorization,'Bearer '+secret);assert.match(init.headers['X-Request-Timestamp'],/^\d{10}$/);const body=JSON.parse(init.body);assert.deepEqual(Object.keys(body).sort(),['messages','model','stream']);assert.equal(body.model,'zhida-fast-1p5');return response();};const input=await data();const a=await runGuide(input,{secret,store,fetcher});assert.equal(a.mode,'live');assert.equal(a.citations[0].author,'宸星');const b=await runGuide(input,{secret,store,fetcher});assert.equal(b.mode,'cached');assert.equal(calls,1);const c=await runGuide({...input,question:'我预算不多，如何试一次？'},{secret,store,fetcher});assert.equal(c.mode,'live');assert.equal(calls,2);const limited=await runGuide({...input,question:'第三次不同问题'},{secret,store,fetcher});assert.equal(limited.mode,'curated');assert.match(limited.reason,/2 次/);assert.equal(calls,2);});
test('invalid generated references and bad JSON fall back honestly',async()=>{for(const value of [JSON.stringify({...answer,source_ids:['invented']}),'not JSON']){const input=await data();const a=await runGuide(input,{secret,store:localStore(),fetcher:async()=>Response.json({choices:[{message:{content:value}}]})});assert.equal(a.mode,'curated');assert.ok(a.reason);assert.equal(a.citations[0].id,'major_first');}});
test('slow provider aborts and same concurrent question issues only one paid request',async()=>{let calls=0;const input=await data();const store=localStore();const fetcher=async(url,init)=>{calls++;return new Promise((resolve,reject)=>init.signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}));};const a=runGuide(input,{secret,store,fetcher,timeoutMs:30});const b=runGuide(input,{secret,store,fetcher,timeoutMs:30});const result=await Promise.all([a,b]);assert.equal(calls,1);assert.ok(result.every(x=>x.mode==='curated'));assert.ok(result.some(x=>/较慢/.test(x.reason)));});
test('requested additional experiences use search, reject external URLs, and retain selected source',async()=>{const calls=[];const input=await data('还有其他人的相似经历吗？');input.source_id='college_planning';const fetcher=async(url,init)=>{calls.push(url);if(url.includes('/zhihu_search'))return Response.json({Code:0,Data:{Items:[{Title:'外部链接',ContentText:'不使用',Url:'https://evil.example/x'},{Title:'一段经历',ContentText:'我安排每周实践。',AuthorName:'作者',Url:'https://www.zhihu.com/question/1/answer/2'}]}});const body=JSON.parse(init.body);const context=body.messages[1].content;assert.ok(context.includes('college_planning'));assert.ok(!context.includes('外部链接'));return response({...answer,source_ids:['college_planning']});};const r=await runGuide(input,{secret,store:localStore(),fetcher});assert.equal(r.mode,'live');assert.deepEqual(r.tools,['知乎搜索','知乎直答']);assert.equal(calls.length,2);assert.equal(safeZhihuUrl('https://zhihu.com.evil.example'),null);assert.equal(safeZhihuUrl('javascript:alert(1)'),null);});
test('durable daily limit applies across sessions and public route rejects other origins',async()=>{const store=localStore();let calls=0;const fetcher=async()=>{calls++;return response();};await runGuide(await data('问题一'),{secret,store,fetcher,dayLimit:1});const second=await runGuide(await data('问题二'),{secret,store,fetcher,dayLimit:1});assert.equal(second.mode,'curated');assert.match(second.reason,/今日/);assert.equal(calls,1);const r=await guideHttp(new Request('https://life.example/api/guide',{method:'POST',headers:{origin:'https://other.example'},body:'{}'}),{ZHIHU_ACCESS_SECRET:secret},{store});assert.equal(r.status,403);});

test('zero daily budget blocks calls and oversized bodies stop before parsing',async()=>{let calls=0;const r=await runGuide(await data(),{secret,store:localStore(),dayLimit:0,fetcher:async()=>{calls++;return response();}});assert.equal(r.mode,'curated');assert.equal(calls,0);const http=await guideHttp(new Request('https://life.example/api/guide',{method:'POST',body:'x'.repeat(9000)}),{ZHIHU_ACCESS_SECRET:secret},{store:localStore()});assert.equal(http.status,413);});
test('follow-up response receives the previous verified exchange',async()=>{const store=localStore(),input=await data();await runGuide(input,{secret,store,fetcher:async()=>response()});let prompt;const r=await runGuide({...input,question:'主要担心成绩',followup:true},{secret,store,fetcher:async(url,init)=>{prompt=JSON.parse(init.body).messages[1].content;return response();}});assert.equal(r.mode,'live');assert.ok(prompt.includes('previous_exchange'));assert.ok(prompt.includes(answer.question));});
