import test from 'node:test';import assert from 'node:assert/strict';import {createState,transition,view} from '../frontend/story.mjs';
const step=(s,type,fields={})=>transition(s,{type,revision:s.revision,node_id:view(s).node_id,...fields});
function chooseSource(s,choice,source){s=step(s,'choose',{choice_id:choice,effort:2});const v=view(s);assert.ok(v.references.some(r=>r.id===source));s=step(s,'select',{source_id:source});return step(s,'advance');}
test('opening presents a protagonist and three consequential choices',()=>{const v=view(createState());assert.equal(v.character.name,'周野');assert.equal(v.node.choices.length,3);assert.match(v.node.narration,/林知夏/);assert.ok(v.node.choices.every(c=>c.gain&&c.cost));});
test('story carries source trail, flags and relationship consequences',()=>{let s=chooseSource(createState(),'project','major_first');assert.equal(s.index,1);assert.equal(s.flags.practice,1);assert.equal(s.history[0].choiceLabel,'跟林知夏做一周的小项目');assert.equal(s.history[0].sourceRole,'inciting_question');s=chooseSource(s,'talk_roommate','college_planning');assert.equal(s.flags.support,1);assert.equal(s.sourceTrail.length,2);assert.match(view(s).node.narration,/林知夏/);});
test('final outcome is derived from accumulated choices rather than eight buttons',()=>{let s=createState();s=chooseSource(s,'project','major_first');s=chooseSource(s,'talk_roommate','college_planning');s=chooseSource(s,'intern','intern_review');const v=view(s);assert.equal(v.node.choices.length,1);s=chooseSource(s,'reply','graduate_three');assert.equal(s.phase,'ending');assert.equal(view(s).ending.title,'先工作，再长出方向');assert.equal(s.history.length,4);});
test('different choices produce distinct endings',()=>{let s=createState();s=chooseSource(s,'study_plan','major_first');s=chooseSource(s,'carry_alone','graduate_work');s=chooseSource(s,'exam_full','graduate_three');s=chooseSource(s,'reply','jobless');assert.equal(view(s).ending.title,'如愿读研，但问题换了');});
test('invalid and stale operations are rejected',()=>{let s=createState();assert.throws(()=>step(s,'choose',{choice_id:'old_ask'}),{code:'INVALID_CHOICE'});s=step(s,'choose',{choice_id:'project'});assert.throws(()=>transition(s,{type:'advance',revision:0,node_id:'freshman_start'}),{code:'STALE_STATE'});assert.throws(()=>step(s,'advance'),{code:'SOURCE_REQUIRED'});});
test('back keeps the story before a choice',()=>{let s=createState();s=step(s,'choose',{choice_id:'rules'});s=step(s,'back');assert.equal(s.phase,'story');assert.equal(s.choiceId,null);assert.equal(s.history.length,0);});
