import {copyFile,mkdir,readFile,writeFile,rm} from 'node:fs/promises';
import {build} from 'esbuild';
const files=['index.html','styles.css','app.mjs','content.mjs','story.mjs','config.js','cover.mjs','branches.mjs','experience.mjs','source-utils.mjs','game.mjs','play-state.mjs','voices.mjs','audio.mjs'];
await rm('dist',{recursive:true,force:true});await mkdir('dist/client',{recursive:true});await mkdir('dist/client/assets',{recursive:true});await mkdir('dist/server',{recursive:true});
const assets={};for(const name of files){await copyFile('frontend/'+name,'dist/client/'+name);assets['/'+name]={body:await readFile('frontend/'+name,'utf8'),type:name.endsWith('.html')?'text/html; charset=utf-8':name.endsWith('.css')?'text/css; charset=utf-8':'text/javascript; charset=utf-8'};}assets['/assets/campus.jpg']={body:Buffer.from(await readFile('frontend/campus.jpg')).toString('base64'),type:'image/jpeg',base64:true};
if(!assets['/index.html'].body.includes((await readFile('VERSION','utf8')).trim()))throw new Error('Missing version');
await writeFile('backend/assets.generated.mjs','export const assets='+JSON.stringify(assets)+';');
await build({entryPoints:['backend/worker.mjs'],outfile:'dist/server/index.js',bundle:true,format:'esm',platform:'browser',target:'es2022',minify:true});
await mkdir('dist/.openai',{recursive:true});await copyFile('.openai/hosting.json','dist/.openai/hosting.json');
await copyFile('frontend/campus.jpg','dist/client/assets/campus.jpg'); console.log('Built Worker and '+files.length+' public assets');
